# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{timed_tables}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Giorgenes"]
  s.date = %q{2010-12-26}
  s.description = %q{}
  s.email = %q{giorgenes@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "app/controllers/timed_tables/timed_tables_controller.rb",
     "app/models/timed_tables/day_row_total.rb",
     "app/models/timed_tables/timed_table.rb",
     "config/routes.rb",
     "lib/engine.rb",
     "db/migrate/20100510210543_create_timed_tables.rb",
     "db/migrate/20100510233541_create_day_row_totals.rb",
     "lib/rails/generators/timed_tables/timed_tables_generator.rb",
     "lib/rails/railties/tasks.rake",
     "lib/timed_tables.rb"
  ]
  s.homepage = %q{http://redmine.vshouse.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{none}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails engine}
  s.add_dependency "rails"         , "~> 3.2.13"
  s.add_development_dependency 'rspec-rails'
  s.add_development_dependency 'factory_girl_rails'
  s.add_development_dependency 'mysql2'
  s.test_files = Dir["spec/**/*"]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

