# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{timed_tables}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Giorgenes"]
  s.date = %q{2010-10-02}
  s.description = %q{}
  s.email = %q{giorgenes@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "app/controllers/application_controller.rb",
     "app/controllers/timed_tables_controller.rb",
     "app/helpers/application_helper.rb",
     "app/helpers/timed_tables_helper.rb",
     "app/models/day_row_total.rb",
     "app/models/timed_table.rb",
     "config/routes.rb",
     "lib/engine.rb",
     "lib/rails/generators/timed_tables/cheese_generator.rb",
     "lib/rails/generators/timed_tables/templates/initializer.rb",
     "lib/rails/generators/timed_tables/templates/migration.rb",
     "lib/rails/generators/timed_tables/templates/schema.rb",
     "lib/rails/railties/tasks.rake",
     "lib/timed_tables.rb"
  ]
  s.homepage = %q{http://redmine.vshouse.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{none}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails engine}
  s.test_files = [
    "test/functional/timed_tables_controller_test.rb",
     "test/performance/browsing_test.rb",
     "test/test_helper.rb",
     "test/unit/day_row_total_test.rb",
     "test/unit/helpers/timed_tables_helper_test.rb",
     "test/unit/timed_table_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

